name: Jira 연동 이슈 생성
description: 이 템플릿을 기반으로 Jira 이슈가 자동으로 생성됩니다.
title: "이슈 제목을 작성해주세요"
labels: ["feat"] # 기본으로 붙일 GitHub 레이블
assignees: []

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "이슈 유형"
      description: "생성할 Jira 이슈의 유형을 선택해주세요."
      options:
        - Task
        - 버그
        - 스토리
        - 에픽
        - 하위 작업
    validations:
      required: true

  - type: input
    id: epic_number
    attributes:
      label: "🎟️ 상위 작업 (Ticket Number)"
      description: "연결할 상위 Jira 에픽이 있다면 이슈 키를 작성해주세요. (선택 사항)"
      placeholder: "예: PROJ-123"

  - type: dropdown
    id: issue_label
    attributes:
      label: "GitHub 레이블 추가"
      description: "이 GitHub 이슈에 추가할 레이블을 선택해주세요. (선택 사항)"
      multiple: true # 여러 개 선택 가능하도록 설정
      options:
        - frontend
        - backend
        - infra
        - urgent
        - 논의필요
        - 개선필요
    validations:
      required: false

  - type: input
    id: branch_name
    attributes:
      label: "🌳 브랜치명 (Branch)"
      description: "자동으로 생성할 브랜치명을 작성해주세요. (선택 사항)"
      placeholder: "예: feature/login"

  - type: textarea
    id: issue_description
    attributes:
      label: "📝 상세 내용(Description)"
      description: "Jira에 등록될 상세 설명을 작성해주세요."
      placeholder: "사용자가 로그인 시 필요한 인증 기능을 제공하여 보안과 사용자 세션을 관리합니다."
    validations:
      required: true

  - type: textarea
    id: task_list
    attributes:
      label: "✅ 체크리스트(Tasks)"
      description: "해당 이슈에 대해 필요한 작업목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
